apiVersion: v1
kind: Namespace
metadata:
  name: infrastructure
  labels:
    name: infrastructure
    monitoring: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: applications
  labels:
    name: applications
    monitoring: enabled